-- ============================================
-- TABELA: usuario
-- ============================================
CREATE TABLE usuario (
  id_usuario INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome VARCHAR(255) NOT NULL,
  email VARCHAR(255) UNIQUE NOT NULL,
  nr_telefone VARCHAR(20) UNIQUE NOT NULL,
  hash VARCHAR(255) NOT NULL,
  dt_primeiro_cadastro TIMESTAMP  NOT NULL DEFAULT CURRENT_TIMESTAMP,
  
  CONSTRAINT check_telefone_e164 
    CHECK (nr_telefone ~ '^\+[1-9]\d{1,14}$'),
  
  CONSTRAINT check_email_formato 
    CHECK (email ~* '^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}$')
);

COMMENT ON COLUMN usuario.nr_telefone IS 
'Número no formato E.164 (+DDI + DDD + Número). Ex: +5561981954455, +14155238548';

-- ============================================
-- TABELA: comunidade
-- ============================================
CREATE TABLE comunidade (
  id_comunidade INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nm_comunidade VARCHAR NOT NULL UNIQUE,
  dt_criacao TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- ============================================
-- TABELA: funcao
-- ============================================
CREATE TABLE funcao (
  id_funcao INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nm_funcao VARCHAR UNIQUE NOT NULL,
  dt_criacao TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- ============================================
-- TABELA: composicao
-- ============================================
CREATE TABLE composicao (
  id_composicao INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_comunidade INTEGER NOT NULL,
  id_usuario INTEGER NOT NULL,
  id_funcao INTEGER NOT NULL,
  dt_inclusao TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  
  CONSTRAINT fk_composicao_comunidade 
    FOREIGN KEY (id_comunidade) REFERENCES comunidade(id_comunidade),
  CONSTRAINT fk_composicao_usuario 
    FOREIGN KEY (id_usuario) REFERENCES usuario(id_usuario),
  CONSTRAINT fk_composicao_funcao 
    FOREIGN KEY (id_funcao) REFERENCES funcao(id_funcao),
  CONSTRAINT uk_composicao_comunidade_usuario 
    UNIQUE (id_comunidade, id_usuario)
);

CREATE INDEX idx_composicao_comunidade ON composicao(id_comunidade);
CREATE INDEX idx_composicao_usuario ON composicao(id_usuario);

-- -- ============================================
-- -- TABELA: categoria
-- -- ============================================
-- CREATE TABLE categoria (
--   id_categoria INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
--   nm_categoria VARCHAR NOT NULL,
--   ds_categoria VARCHAR NOT NULL,
--   dt_criacao TIMESTAMP DEFAULT CURRENT_TIMESTAMP
-- );

-- COMMENT ON COLUMN categoria.nm_categoria IS 
-- 'Doméstica, Alimentação, Agendamentos, Pessoal';

-- -- ============================================
-- -- TABELA: subcategoria
-- -- ============================================
-- CREATE TABLE subcategoria (
--   id_subcategoria INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
--   id_categoria INTEGER NOT NULL,
--   nm_subcategoria VARCHAR NOT NULL,
--   ds_subcategoria VARCHAR NOT NULL,
--   dt_criacao TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  
--   CONSTRAINT fk_subcategoria_categoria 
--     FOREIGN KEY (id_categoria) REFERENCES categoria(id_categoria)
-- );

-- CREATE INDEX idx_subcategoria_categoria ON subcategoria(id_categoria);

-- COMMENT ON COLUMN subcategoria.nm_subcategoria IS 
-- 'Limpeza, Refeições, Compras, etc';

-- -- ============================================
-- -- TABELA: tarefa
-- -- ============================================
-- CREATE TABLE tarefa (
--   id_tarefa INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
--   id_subcategoria INTEGER NOT NULL,
--   nm_tarefa VARCHAR NOT NULL,
--   ds_tarefa VARCHAR NOT NULL,
--   dt_criacao TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  
--   CONSTRAINT fk_tarefa_subcategoria 
--     FOREIGN KEY (id_subcategoria) REFERENCES subcategoria(id_subcategoria)
-- );

-- CREATE INDEX idx_tarefa_subcategoria ON tarefa(id_subcategoria);

-- COMMENT ON COLUMN tarefa.nm_tarefa IS 
-- 'Limpar Cômodo, Lavar Louça, etc';

-- -- ============================================
-- -- TABELA: tipo_atributo
-- -- ============================================
-- CREATE TABLE tipo_atributo (
--   id_tipo_atributo INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
--   nm_tipo_atributo VARCHAR UNIQUE NOT NULL,
--   dt_criacao TIMESTAMP DEFAULT CURRENT_TIMESTAMP
-- );

-- COMMENT ON COLUMN tipo_atributo.nm_tipo_atributo IS 
-- 'Cômodo, Item, Pessoa, etc';

-- -- ============================================
-- -- TABELA: valor_atributo
-- -- ============================================
-- CREATE TABLE valor_atributo (
--   id_valor_atributo INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
--   id_tipo_atributo INTEGER NOT NULL,
--   valor_atributo VARCHAR NOT NULL,
--   dt_criacao TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  
--   CONSTRAINT fk_valor_atributo_tipo 
--     FOREIGN KEY (id_tipo_atributo) REFERENCES tipo_atributo(id_tipo_atributo)
-- );

-- CREATE INDEX idx_valor_atributo_tipo ON valor_atributo(id_tipo_atributo);

-- COMMENT ON COLUMN valor_atributo.valor_atributo IS 
-- 'Sala, Cozinha, Arroz, Feijão';

-- -- ============================================
-- -- TABELA: atributo_tarefa
-- -- ============================================
-- CREATE TABLE atributo_tarefa (
--   id_atributo INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
--   id_tarefa INTEGER NOT NULL,
--   id_valor_atributo INTEGER NOT NULL,
--   dt_criacao TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  
--   CONSTRAINT fk_atributo_tarefa_tarefa 
--     FOREIGN KEY (id_tarefa) REFERENCES tarefa(id_tarefa),
--   CONSTRAINT fk_atributo_tarefa_valor 
--     FOREIGN KEY (id_valor_atributo) REFERENCES valor_atributo(id_valor_atributo)
-- );

-- CREATE INDEX idx_atributo_tarefa_tarefa ON atributo_tarefa(id_tarefa);
-- CREATE INDEX idx_atributo_tarefa_valor ON atributo_tarefa(id_valor_atributo);

-- -- ============================================
-- -- TABELA: atribuicao_tarefa
-- -- ============================================
-- CREATE TABLE atribuicao_tarefa (
--   id_atribuicao INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
--   id_tarefa INTEGER NOT NULL,
--   id_comunidade INTEGER NOT NULL,
--   dt_criacao TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  
--   CONSTRAINT fk_atribuicao_tarefa_tarefa 
--     FOREIGN KEY (id_tarefa) REFERENCES tarefa(id_tarefa),
--   CONSTRAINT fk_atribuicao_tarefa_comunidade 
--     FOREIGN KEY (id_comunidade) REFERENCES comunidade(id_comunidade)
-- );

-- CREATE INDEX idx_atribuicao_tarefa_tarefa ON atribuicao_tarefa(id_tarefa);
-- CREATE INDEX idx_atribuicao_tarefa_comunidade ON atribuicao_tarefa(id_comunidade);

-- -- ============================================
-- -- TABELA: responsavel_tarefa
-- -- ============================================
-- CREATE TABLE responsavel_tarefa (
--   id_responsavel_tarefa INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
--   id_atribuicao INTEGER NOT NULL,
--   id_usuario INTEGER NOT NULL,
--   eh_principal BOOLEAN DEFAULT false,
--   dt_inclusao TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  
--   CONSTRAINT fk_responsavel_tarefa_atribuicao 
--     FOREIGN KEY (id_atribuicao) REFERENCES atribuicao_tarefa(id_atribuicao),
--   CONSTRAINT fk_responsavel_tarefa_usuario 
--     FOREIGN KEY (id_usuario) REFERENCES usuario(id_usuario),
--   CONSTRAINT uk_responsavel_atribuicao_usuario 
--     UNIQUE (id_atribuicao, id_usuario)
-- );

-- CREATE INDEX idx_responsavel_tarefa_atribuicao ON responsavel_tarefa(id_atribuicao);
-- CREATE INDEX idx_responsavel_tarefa_usuario ON responsavel_tarefa(id_usuario);

-- -- ============================================
-- -- TABELA: tipo_periodicidade
-- -- ============================================
-- CREATE TABLE tipo_periodicidade (
--   id_tipo_periodicidade INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
--   nm_tipo VARCHAR UNIQUE NOT NULL,
--   dt_criacao TIMESTAMP DEFAULT CURRENT_TIMESTAMP
-- );

-- COMMENT ON COLUMN tipo_periodicidade.nm_tipo IS 
-- 'Diária, Semanal, Quinzenal, Mensal, A cada N dias, Data Específica';

-- -- ============================================
-- -- TABELA: periodicidade
-- -- ============================================
-- CREATE TABLE periodicidade (
--   id_periodicidade INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
--   id_responsavel_tarefa INTEGER NOT NULL,
--   id_tipo_periodicidade INTEGER NOT NULL,
--   dias_intervalo INTEGER,
--   data_especifica DATE,
--   dias_semana VARCHAR,
--   dt_criacao TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  
--   CONSTRAINT fk_periodicidade_responsavel 
--     FOREIGN KEY (id_responsavel_tarefa) REFERENCES responsavel_tarefa(id_responsavel_tarefa),
--   CONSTRAINT fk_periodicidade_tipo 
--     FOREIGN KEY (id_tipo_periodicidade) REFERENCES tipo_periodicidade(id_tipo_periodicidade)
-- );

-- CREATE INDEX idx_periodicidade_responsavel ON periodicidade(id_responsavel_tarefa);

-- COMMENT ON COLUMN periodicidade.dias_intervalo IS 
-- 'Para "A cada N dias"';
-- COMMENT ON COLUMN periodicidade.data_especifica IS 
-- 'Para "Data Específica" (ex: 25/01/2026)';
-- COMMENT ON COLUMN periodicidade.dias_semana IS 
-- 'Para "Semanal" (seg,ter,qua,qui,sex,sab,dom)';

-- -- ============================================
-- -- TABELA: configuracao_notificacao
-- -- ============================================
-- CREATE TABLE configuracao_notificacao (
--   id_config_notificacao INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
--   id_responsavel_tarefa INTEGER NOT NULL,
--   frequencia_notificacao VARCHAR NOT NULL,
--   horario_notificacao TIME,
--   ativo BOOLEAN DEFAULT true,
--   dt_criacao TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  
--   CONSTRAINT fk_config_notificacao_responsavel 
--     FOREIGN KEY (id_responsavel_tarefa) REFERENCES responsavel_tarefa(id_responsavel_tarefa)
-- );

-- CREATE INDEX idx_config_notificacao_responsavel ON configuracao_notificacao(id_responsavel_tarefa);

-- COMMENT ON COLUMN configuracao_notificacao.frequencia_notificacao IS 
-- 'Diária, A cada 2 dias, Semanal, etc';
-- COMMENT ON COLUMN configuracao_notificacao.horario_notificacao IS 
-- 'Hora para enviar a notificação';

-- -- ============================================
-- -- TABELA: historico_notificacao
-- -- ============================================
-- CREATE TABLE historico_notificacao (
--   id_historico INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
--   id_config_notificacao INTEGER NOT NULL,
--   data_envio TIMESTAMP,
--   status VARCHAR NOT NULL,
--   tarefas_incluidas TEXT,
--   dt_criacao TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  
--   CONSTRAINT fk_historico_notificacao_config 
--     FOREIGN KEY (id_config_notificacao) REFERENCES configuracao_notificacao(id_config_notificacao)
-- );

-- CREATE INDEX idx_historico_notificacao_config ON historico_notificacao(id_config_notificacao);
-- CREATE INDEX idx_historico_notificacao_data ON historico_notificacao(data_envio);

-- COMMENT ON COLUMN historico_notificacao.status IS 
-- 'enviada, falha, pendente';
-- COMMENT ON COLUMN historico_notificacao.tarefas_incluidas IS 
-- 'JSON array com IDs das tarefas enviadas';