-- ============================================
-- TABELA: usuario
-- ============================================
CREATE TABLE usuario (
  id_usuario INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome VARCHAR(255) NOT NULL,
  email VARCHAR(255) UNIQUE NOT NULL,
  nr_telefone VARCHAR(20) UNIQUE NOT NULL,
  hash VARCHAR(255) NOT NULL,
  dt_primeiro_cadastro TIMESTAMP  NOT NULL DEFAULT CURRENT_TIMESTAMP,
  
  CONSTRAINT check_telefone_e164 
    CHECK (nr_telefone ~ '^\+[1-9]\d{1,14}$'),
  
  CONSTRAINT check_email_formato 
    CHECK (email ~* '^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}$')
);

COMMENT ON COLUMN usuario.nr_telefone IS 
'Número no formato E.164 (+DDI + DDD + Número). Ex: +5561981954455, +14155238548';

-- ============================================
-- TABELA: comunidade
-- ============================================
CREATE TABLE comunidade (
  id_comunidade INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nm_comunidade VARCHAR NOT NULL UNIQUE,
  dt_criacao TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- ============================================
-- TABELA: funcao
-- ============================================
CREATE TABLE funcao (
  id_funcao INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nm_funcao VARCHAR UNIQUE NOT NULL,
  dt_criacao TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- ============================================
-- TABELA: composicao
-- ============================================
CREATE TABLE composicao (
  id_composicao INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_comunidade INTEGER NOT NULL,
  id_usuario INTEGER NOT NULL,
  id_funcao INTEGER NOT NULL,
  dt_inclusao TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  
  CONSTRAINT fk_composicao_comunidade 
    FOREIGN KEY (id_comunidade) REFERENCES comunidade(id_comunidade),
  CONSTRAINT fk_composicao_usuario 
    FOREIGN KEY (id_usuario) REFERENCES usuario(id_usuario),
  CONSTRAINT fk_composicao_funcao 
    FOREIGN KEY (id_funcao) REFERENCES funcao(id_funcao),
  CONSTRAINT uk_composicao_comunidade_usuario 
    UNIQUE (id_comunidade, id_usuario)
);

CREATE INDEX idx_composicao_comunidade ON composicao(id_comunidade);
CREATE INDEX idx_composicao_usuario ON composicao(id_usuario);

-- ============================================
-- TABELA: tarefa
-- ============================================
CREATE TABLE tarefa (
  id_tarefa INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nm_tarefa VARCHAR NOT NULL,
  dt_criacao TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
);

CREATE INDEX idx_tarefa_subcategoria ON tarefa(id_subcategoria);


-- ============================================
-- TABELA: atribuicao
-- ============================================
CREATE TABLE atribuicao (
  id_atribuicao INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_usuario INTEGER NOT NULL,
  id_comunidade INTEGER NOT NULL,
  id_tarefa INTEGER NOT NULL,
  dt_atribuicao TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  
  CONSTRAINT fk_atribuicao_usuario 
    FOREIGN KEY (id_usuario) REFERENCES usuario(id_usuario),
  CONSTRAINT fk_atribuicao_comunidade 
    FOREIGN KEY (id_comunidade) REFERENCES comunidade(id_comunidade),
  CONSTRAINT fk_atribuicao_tarefa 
    FOREIGN KEY (id_tarefa) REFERENCES tarefa(id_tarefa),
  CONSTRAINT uk_atribuicao_usuario_tarefa
    UNIQUE (id_usuario, id_tarefa, id_comunidade)
);

CREATE INDEX idx_atribuicao_usuario ON atribuicao(id_usuario);
CREATE INDEX idx_atribuicao_comunidade ON atribuicao(id_comunidade);
CREATE INDEX idx_atribuicao_tarefa ON atribuicao(id_tarefa);

COMMENT ON TABLE atribuicao IS 
'Vincula tarefas aos usuários de uma comunidade. Ex: Fulano (usuário) → Lavar louça (tarefa) → Família Silva (comunidade)';

-- ============================================
-- ALTER TABLE: tarefa
-- ============================================
ALTER TABLE tarefa 
ADD COLUMN eh_recorrente BOOLEAN NOT NULL DEFAULT false;

-- ============================================
-- TABELA: periodicidade
-- ============================================
CREATE TABLE periodicidade (
  id_periodicidade INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ds_periodicidade VARCHAR NOT NULL,
  dt_criacao TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO periodicidade (id_periodicidade, ds_periodicidade) VALUES
(1, 'Diário'),
(2, 'Dias específicos da semana'),
(3, 'Dias específicos do mês'),
(4, 'A cada n dias'),
(5, 'Data específica');

-- ============================================
-- TABELA: tarefa_periodicidade
-- ============================================
CREATE TABLE tarefa_periodicidade (
  id_tarefa_periodicidade INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_tarefa INTEGER NOT NULL,
  id_periodicidade INTEGER NOT NULL,
  dt_criacao TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  
  CONSTRAINT fk_tarefa_periodicidade_tarefa 
    FOREIGN KEY (id_tarefa) REFERENCES tarefa(id_tarefa),
  CONSTRAINT fk_tarefa_periodicidade_periodicidade 
    FOREIGN KEY (id_periodicidade) REFERENCES periodicidade(id_periodicidade),
  CONSTRAINT uk_tarefa_periodicidade_unica
    UNIQUE (id_tarefa, id_periodicidade)
);

-- ============================================
-- TABELA: periodicidade_dia_semana
-- ============================================
CREATE TABLE periodicidade_dia_semana (
  id_periodicidade_dia_semana INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_tarefa_periodicidade INTEGER NOT NULL,
  dia_semana INTEGER NOT NULL,
  
  CONSTRAINT fk_dia_semana_tarefa_periodicidade 
    FOREIGN KEY (id_tarefa_periodicidade) REFERENCES tarefa_periodicidade(id_tarefa_periodicidade),
  CONSTRAINT check_dia_semana_valido
    CHECK (dia_semana BETWEEN 1 AND 7)
);

COMMENT ON COLUMN periodicidade_dia_semana.dia_semana IS 
'1=Segunda, 2=Terça, 3=Quarta, 4=Quinta, 5=Sexta, 6=Sábado, 7=Domingo';

-- ============================================
-- TABELA: periodicidade_dia_mes
-- ============================================
CREATE TABLE periodicidade_dia_mes (
  id_periodicidade_dia_mes INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_tarefa_periodicidade INTEGER NOT NULL,
  dia_mes INTEGER NOT NULL,
  
  CONSTRAINT fk_dia_mes_tarefa_periodicidade 
    FOREIGN KEY (id_tarefa_periodicidade) REFERENCES tarefa_periodicidade(id_tarefa_periodicidade),
  CONSTRAINT check_dia_mes_valido
    CHECK (dia_mes BETWEEN 1 AND 31)
);

-- ============================================
-- TABELA: periodicidade_intervalo
-- ============================================
CREATE TABLE periodicidade_intervalo (
  id_periodicidade_intervalo INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_tarefa_periodicidade INTEGER NOT NULL,
  intervalo_dias INTEGER NOT NULL,
  dt_inicio DATE DEFAULT CURRENT_DATE,
  
  CONSTRAINT fk_intervalo_tarefa_periodicidade 
    FOREIGN KEY (id_tarefa_periodicidade) REFERENCES tarefa_periodicidade(id_tarefa_periodicidade),
  CONSTRAINT check_intervalo_positivo
    CHECK (intervalo_dias > 0)
);

-- ============================================
-- TABELA: periodicidade_data_especifica
-- ============================================
CREATE TABLE periodicidade_data_especifica (
  id_periodicidade_data_especifica INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_tarefa_periodicidade INTEGER NOT NULL,
  dt_especifica DATE NOT NULL,
  
  CONSTRAINT fk_data_especifica_tarefa_periodicidade 
    FOREIGN KEY (id_tarefa_periodicidade) REFERENCES tarefa_periodicidade(id_tarefa_periodicidade)
);